apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.jobserver.service.servicePort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "spark-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
