kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "log-archival.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "db": {
        "name": "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user": "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "log-archival.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }},
        "max_open_connections": {{ .Values.db.max_open_connections }},
        "max_idle_connections": {{ .Values.db.max_idle_connections }}
      },
      "serverPort": "{{ .Values.serverPort }}",
      "kafkaBrokers": "{{ .Values.global.kafkaBrokers }}"
    }
