apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
