{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dataset-raw-controller.fullname" . }}
  labels:
    {{- include "dataset-raw-controller.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dataset-raw-controller.fullname" . }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleDownPeriod }}
        value: 1
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleUpPeriod }}
        value: 1
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: event_queue_handler_occupancy_percent
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.eventQueueHandlerOccupancyPercentage }}
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}