apiVersion: v1
kind: Service
metadata:
  name: {{ include "raw-query-exec-controller.fullname" . }}
  labels:
    {{- include "raw-query-exec-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "raw-query-exec-controller.selectorLabels" . | nindent 4 }}
