kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "compaction-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "compactionURL": "http://{{ template "compaction-controller.fullname" . }}",
      "datasetControllerURL": "http://{{ template "compaction-controller.dataset-controller.fullname" . }}",
      "datasetRawControllerURL": "http://{{ template "compaction-controller.dataset-raw-controller.fullname" . }}",
      "db": {
        "name": "{{ .Values.global.postgresql.postgresqlDatabase }}",
        "user": "{{ .Values.global.postgresql.postgresqlUsername }}",
        "password": "{{ .Values.global.postgresql.postgresqlPassword }}",
        "host": "{{ template "compaction-controller.postgresql.fullname" . }}",
        "port": {{ .Values.global.postgresql.servicePort }},
        "max_open_connections": {{ .Values.db.max_open_connections }},
        "max_idle_connections": {{ .Values.db.max_idle_connections }}
      },
      "jobServer": "http://{{ template "compaction-controller.spark-manager.fullname" . }}",
      "serverPort": "{{ .Values.serverPort }}",
      "ingestControllerURL": "http://{{ template "compaction-controller.ingest-controller.fullname" . }}",
      "maxRunning": {{ .Values.maxSimultaneousRun }},
      "maxAttempts": {{ .Values.maxAttempts }},
      "pendingStateTolerationHours": {{ .Values.maxPendingHours }},
      "runningStateTolerationHours": {{ .Values.maxRunningHours }},
      "compactedStateTolerationHours": {{ .Values.maxCompactedHours }}
    }
