apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataset-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.service.servicePort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "dataset-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}