apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-history-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark-history-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  enablePVC: {{ .Values.pvc.enablePVC | quote }}
  enableGCS: {{ .Values.global.secrets.gcs.enable | quote }}
  enableS3: {{ .Values.global.secrets.aws.enable | quote }}
  enableWASBS: {{ .Values.wasbs.enableWASBS | quote }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.pvc.enablePVC }}
  {{- range $key, $val := omit .Values.pvc "enablePVC" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.global.secrets.gcs.enable }}
  enableIAM: "true"
  {{- range $key, $val := .Values.gcs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.global.secrets.aws.enable }}
  enableIAM: {{ .Values.global.secrets.aws.use_iam_role | quote }}
  awsAccessKeyID: {{ .Values.global.secrets.aws.AWS_ACCESS_KEY_ID | quote }}
  awsSecretAccessKey: {{ .Values.global.secrets.aws.AWS_SECRET_ACCESS_KEY | quote }}
  {{- range $key, $val := .Values.s3 }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.global.secrets.azure.enable }}
  storageAccountName: {{ .Values.global.secrets.azure.STORAGE_ACCOUNT_NAME | quote }}
  storageAccountKey: {{ .Values.global.secrets.azure.STORAGE_ACCOUNT_ACCESS_KEY | quote }}
  containerName: {{ .Values.global.secrets.azure.SPARK_HS_CONTAINER_NAME | quote }}
  {{- else if .Values.wasbs.enableWASBS }}
  {{- range $key, $val := omit .Values.wasbs "enableWASBS" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.hdfs.enableHDFS }}
  {{- range $key, $val := .Values.hdfs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
