{{- if (or (and .Values.global.secrets.aws.enable (not .Values.global.secrets.aws.use_iam_role)) .Values.global.secrets.azure.enable) }}
{{- if and .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-history-server.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    helm.sh/chart: {{ include "spark-history-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}
