apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.datanode.service" . }}
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.datanode.port }}
      name: datanode
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}-datanode
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
