apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.server.service" . }}
  labels:
    {{- include "hive.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.hiveServer.port }}
    name: server
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hive.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
