apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.metastore.service" . }}-external
  labels:
    {{- include "hive.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.hiveMetastore.port }}
    name: metastore-ext
    nodePort: {{ .Values.service.hiveMetastore.externalPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hive.name" . }}-metastore
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
